modLoader = "javafml"
loaderVersion = "${FORGE_LOADER}"
issueTrackerURL = "${GIT_REPO}/issues"
license = "MIT"
[[mods]]
modId = "${MODID}"
updateJSONURL = "https://updates.blamejared.com/get?n=${MODID}&gv=${MINECRAFT}&ml=forge"
version = "${version}"
displayName = "${NAME}"
displayURL = "${CURSE_HOMEPAGE}"
authors = "${AUTHOR}"
logoFile = "icon.png"
description = '''${DESCRIPTION}'''
itemIcon = "${ITEM_ICON}"
[[dependencies.${MODID}]]
modId = "forge"
mandatory = true
versionRange = "${FORGE_LOADER}"
ordering = "NONE"
side = "CLIENT"
[[dependencies.${MODID}]]
modId = "minecraft"
mandatory = true
versionRange = "[${MINECRAFT}]"
ordering = "NONE"
side = "CLIENT"
[[dependencies.${MODID}]]
modId = "searchables"
mandatory = true
versionRange = "[${SEARCHABLES},)"
ordering = "NONE"
side = "CLIENT"